 
# door_adapter_mock parameters

doors:
  - door1
  - door2
# Add new door names here. Ensure that door names matches what is defined in RMF Map.

door_subscriber:
  topic_name: "adapter_door_requests"

door_publisher:
  topic_name: "door_states"
  door_state_publish_period: 1.0 # Seconds